import {
  charactersBackImages,
  charactersFullImages,
  charactersMiniImages,
  circleLogoImages,
} from "./charactersImages";

export interface ICharacterData {
  id: number;
  name: string;
  status: string;
  imgFull: string;
  imgMini: string;
  imgBack: string;
  race: string;
  description: string;
  positionFullImg: string; // Pretty bad practice, but it's the best way to do it without changing the images source and therefore have a smooth transition
  circleLogo: string;
  color: string;
  strength: number;
  vitality: number;
  magic: number;
  speed: number;
  inteligence: number;
}

export const charactersData: ICharacterData[] = [
  {
    id: 1,
    name: "Link",
    status: "Hero",
    imgFull: charactersFullImages.linkFullImg,
    imgMini: charactersMiniImages.linkMiniImg,
    imgBack: charactersBackImages.linkBackImg,
    race: "Hylian",
    description: "The hero of Hyrule, who is fated to wield the Master Sword.",
    positionFullImg: "object-[40%,0%]",
    circleLogo: circleLogoImages.circleYellow,
    color: "#FFD700",
    strength: 8,
    vitality: 9,
    magic: 4,
    speed: 9,
    inteligence: 8,
  },
  {
    id: 2,
    name: "Zelda",
    status: "Princess",
    imgFull: charactersFullImages.zeldaFullImg,
    imgMini: charactersMiniImages.zeldaMiniImg,
    imgBack: charactersBackImages.zeldaBackImg,
    race: "Hylian",
    description:
      "The princess of Hyrule, who possesses the blood of the goddess Hylia.",
    positionFullImg: "object-[50%,0%]",
    circleLogo: circleLogoImages.circleYellow,
    color: "#FFD700",
    strength: 3,
    vitality: 5,
    magic: 8,
    speed: 3,
    inteligence: 10,
  },
  {
    id: 3,
    name: "Ganon",
    status: "Calamity",
    imgFull: charactersFullImages.ganonFullImg,
    imgMini: charactersMiniImages.ganonMiniImg,
    imgBack: charactersBackImages.ganonBackImg,
    race: "Gerudo",
    description:
      "The calamitous form of Ganondorf, who has given up on reincarnation and assumed his pure, enraged form.",
    positionFullImg: "object-[55%,0%]",
    circleLogo: circleLogoImages.circleRed,
    color: "#DC143C",
    strength: 10,
    vitality: 10,
    magic: 10,
    speed: 10,
    inteligence: 10,
  },
  {
    id: 4,
    name: "Tulin",
    status: "Warrior",
    imgFull: charactersFullImages.tulinFullImg,
    imgMini: charactersMiniImages.tulinMiniImg,
    imgBack: charactersBackImages.tulinBackImg,
    race: "Rito",
    description:
      "A young warrior who is dedicated to the protection of Hyrule.",
    positionFullImg: "object-[37%,0%]",
    circleLogo: circleLogoImages.circleWhite,
    color: "#FFFFFF",
    strength: 6,
    vitality: 6,
    magic: 3,
    speed: 10,
    inteligence: 5,
  },
  {
    id: 5,
    name: "Riju",
    status: "Chief",
    imgFull: charactersFullImages.rijuFullImg,
    imgMini: charactersMiniImages.rijuMiniImg,
    imgBack: charactersBackImages.rijuBackImg,
    race: "Gerudo",
    description: "The chief of the Gerudo, who is wise beyond her years.",
    positionFullImg: "object-[37%,0%]",
    circleLogo: circleLogoImages.circleYellow,
    color: "#FFD700",
    strength: 9,
    vitality: 6,
    magic: 5,
    speed: 7,
    inteligence: 5,
  },
  {
    id: 6,
    name: "Sidon",
    status: "Prince",
    imgFull: charactersFullImages.sidonFullImg,
    imgMini: charactersMiniImages.sidonMiniImg,
    imgBack: charactersBackImages.sidonBackImg,
    race: "Zora",
    description:
      "The prince of the Zora, who possesses powerful swimming skills.",
    positionFullImg: "object-[65%,0%]",
    circleLogo: circleLogoImages.circleBlue,
    color: "#1E90FF",
    strength: 7,
    vitality: 9,
    magic: 3,
    speed: 7,
    inteligence: 4,
  },
  {
    id: 7,
    name: "Yunobo",
    status: "Goron",
    imgFull: charactersFullImages.yunoboFullImg,
    imgMini: charactersMiniImages.yunoboMiniImg,
    imgBack: charactersBackImages.yunoboBackImg,
    race: "Goron",
    description: "A young Goron who is a descendant of the great Daruk.",
    positionFullImg: "object-[50%,0%]",
    circleLogo: circleLogoImages.circleRed,
    color: "#DC143C",
    strength: 9,
    vitality: 5,
    magic: 3,
    speed: 3,
    inteligence: 3,
  },
  {
    id: 8,
    name: "Paya",
    status: "Sheikah",
    imgFull: charactersFullImages.payaFullImg,
    imgMini: charactersMiniImages.payaMiniImg,
    imgBack: charactersBackImages.payaBackImg,
    race: "Sheikah",
    description: "A young Sheikah who is devoted to her research.",
    positionFullImg: "object-[37%,0%]",
    circleLogo: circleLogoImages.circleGreen,
    color: "#008000",
    strength: 3,
    vitality: 6,
    magic: 6,
    speed: 4,
    inteligence: 10,
  },
  {
    id: 9,
    name: "Rauru",
    status: "Sage",
    imgFull: charactersFullImages.rauruFullImg,
    imgMini: charactersMiniImages.rauruMiniImg,
    imgBack: charactersBackImages.rauruBackImg,
    race: "Hylian",
    description:
      "The Sage of Light, who is dedicated to the protection of the Triforce.",
    positionFullImg: "object-[37%,0%]",
    circleLogo: circleLogoImages.circleYellow,
    color: "#FFD700",
    strength: 3,
    vitality: 10,
    magic: 6,
    speed: 4,
    inteligence: 10,
  },
  {
    id: 10,
    name: "Kohga",
    status: "Leader",
    imgFull: charactersFullImages.kohgaFullImg,
    imgMini: charactersMiniImages.kohgaMiniImg,
    imgBack: charactersBackImages.kohgaBackImg,
    race: "Yiga",
    description:
      "The leader of the Yiga Clan, who is dedicated to the resurrection of Ganon.",
    positionFullImg: "object-[37%,0%]",
    circleLogo: circleLogoImages.circleRed,
    color: "#DC143C",
    strength: 2,
    vitality: 3,
    magic: 2,
    speed: 3,
    inteligence: 2,
  },
  {
    id: 11,
    name: "Purah",
    status: "Researcher",
    imgFull: charactersFullImages.purahFullImg,
    imgMini: charactersMiniImages.purahMiniImg,
    imgBack: charactersBackImages.purahBackImg,
    race: "Sheikah",
    description:
      "A Sheikah researcher who is dedicated to the study of ancient technology.",
    positionFullImg: "object-[25%,0%]",
    circleLogo: circleLogoImages.circleGreen,
    color: "#008000",
    strength: 3,
    vitality: 6,
    magic: 6,
    speed: 4,
    inteligence: 10,
  },
  {
    id: 12,
    name: "Mojo",
    status: "Merchant",
    imgFull: charactersFullImages.mojoFullImg,
    imgMini: charactersMiniImages.mojoMiniImg,
    imgBack: charactersBackImages.mojoBackImg,
    race: "Tree",
    description:
      "A giant tree who is dedicated to the protection of the forest.",
    positionFullImg: "object-[57%,0%]",
    circleLogo: circleLogoImages.circleGreen,
    color: "#008000",
    strength: 0,
    vitality: 10,
    magic: 10,
    speed: 0,
    inteligence: 10,
  },
];
